apiVersion: v1
kind: Pod
metadata:
  name: "my-pod"
  namespace: default
  labels:
    app: "my-pod"
spec:
  containers:
    - name: my-pod
      image: "nginx:latest"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
