apiVersion: v1
kind: Pod
metadata:
  name: "my-pod"
  namespace: default
  labels:
    app: "my-pod"
spec:
  containers:
    - name: my-pod
      image: "nginx:latest"
      ports:
        - containerPort: 80
