apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
spec:
  capacity:
    storage: 2Gi
  hostpath:
    path: /tmp/pv
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: default
  labels:
    app: pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: frontend
spec:
  volumes:
    - name: persistent-volumes
      persistentVolumeClaim:
        claimName: pvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /home
          name: persistent-volumes
