apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels:
    app: my-replica
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
        - name: my-replica
          image: "nginx:latest"
          ports:
            - containerPort: 80
