apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "2"
    persistentvolumeclaims: "5"
    requests.storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: "my-pod"
  namespace: dev
  labels:
    app: "my-pod"
spec:
  containers:
    - name: my-pod
      image: "nginx:latest"
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
