apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stateful
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-stateful # has to match .spec.template.metadata.labels
  replicas: 3
  template:
    metadata:
      labels:
        app: my-stateful # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: my-stateful
          image: my-stateful-slim:1.16.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
